# Generated by Django 2.2.9 on 2021-10-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20211002_0101'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='post',
            order_with_respect_to='pub_date',
        ),
    ]
