# Generated by Django 2.2.9 on 2021-10-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20211003_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='post',
            order_with_respect_to=None,
        ),
    ]
